[2021-06-08 15:44:44,433] [autoreload.py:636] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2021-06-08 15:46:44,871] [autoreload.py:636] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2021-06-08 15:47:01,863] [autoreload.py:636] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2021-06-08 15:47:33,345] [autoreload.py:636] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2021-06-08 15:47:34,914] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET / HTTP/1.1" 200 20506
[2021-06-08 15:47:35,549] [basehttp.py:75] [basehttp:handle_error] [INFO]- - Broken pipe from ('127.0.0.1', 61344)

[2021-06-08 15:47:38,229] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET / HTTP/1.1" 200 20506
[2021-06-08 15:47:38,822] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /static/js/axios-0.18.0.min.js HTTP/1.1" 304 0
[2021-06-08 15:47:38,986] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /static/js/common.js HTTP/1.1" 200 891
[2021-06-08 15:47:39,002] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /static/js/index.js HTTP/1.1" 200 1381
[2021-06-08 15:47:39,311] [log.py:224] [log:log_response] [WARNING]- Not Found: /carts/simple/
[2021-06-08 15:47:39,332] [basehttp.py:161] [basehttp:log_message] [WARNING]- "GET /carts/simple/ HTTP/1.1" 404 4047
[2021-06-08 15:47:39,350] [log.py:224] [log:log_response] [WARNING]- Not Found: /favicon.ico
[2021-06-08 15:47:39,352] [basehttp.py:161] [basehttp:log_message] [WARNING]- "GET /favicon.ico HTTP/1.1" 404 4041
[2021-06-08 15:48:20,544] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET / HTTP/1.1" 200 20506
[2021-06-08 15:48:20,591] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /static/css/reset.css HTTP/1.1" 200 638
[2021-06-08 15:48:20,595] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /static/css/main.css HTTP/1.1" 200 39722
[2021-06-08 15:48:20,599] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /static/js/axios-0.18.0.min.js HTTP/1.1" 200 12913
[2021-06-08 15:48:20,604] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /static/js/jquery-1.12.4.min.js HTTP/1.1" 200 97169
[2021-06-08 15:48:20,610] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /static/js/common.js HTTP/1.1" 200 891
[2021-06-08 15:48:20,614] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /static/js/vue-2.5.16.js HTTP/1.1" 200 289387
[2021-06-08 15:48:20,620] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /static/js/slide.js HTTP/1.1" 200 1822
[2021-06-08 15:48:20,636] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /static/images/goods/goods001.jpg HTTP/1.1" 200 5391
[2021-06-08 15:48:20,636] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /static/js/index.js HTTP/1.1" 200 1381
[2021-06-08 15:48:20,636] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /static/images/logo.png HTTP/1.1" 200 7450
[2021-06-08 15:48:20,637] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /static/images/goods/goods003.jpg HTTP/1.1" 200 8579
[2021-06-08 15:48:20,637] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /static/images/goods/goods002.jpg HTTP/1.1" 200 5377
[2021-06-08 15:48:20,650] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /static/images/slide01.jpg HTTP/1.1" 200 67813
[2021-06-08 15:48:20,654] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /static/images/banner01.jpg HTTP/1.1" 200 23658
[2021-06-08 15:48:20,660] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /static/images/adv01.jpg HTTP/1.1" 200 39831
[2021-06-08 15:48:20,665] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /static/images/slide03.jpg HTTP/1.1" 200 70152
[2021-06-08 15:48:20,668] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /static/images/goods/goods004.jpg HTTP/1.1" 200 6565
[2021-06-08 15:48:20,670] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /static/images/slide02.jpg HTTP/1.1" 200 89905
[2021-06-08 15:48:20,671] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /static/images/goods/goods005.jpg HTTP/1.1" 200 7578
[2021-06-08 15:48:20,672] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /static/images/slide04.jpg HTTP/1.1" 200 107973
[2021-06-08 15:48:20,681] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /static/images/banner02.jpg HTTP/1.1" 200 26729
[2021-06-08 15:48:20,688] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /static/images/goods/goods008.jpg HTTP/1.1" 200 7072
[2021-06-08 15:48:20,689] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /static/images/goods/goods009.jpg HTTP/1.1" 200 8738
[2021-06-08 15:48:20,690] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /static/images/icons.png HTTP/1.1" 200 7740
[2021-06-08 15:48:20,692] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /static/images/banner03.jpg HTTP/1.1" 200 22681
[2021-06-08 15:48:20,742] [log.py:224] [log:log_response] [WARNING]- Not Found: /carts/simple/
[2021-06-08 15:48:20,743] [basehttp.py:161] [basehttp:log_message] [WARNING]- "GET /carts/simple/ HTTP/1.1" 404 4047
[2021-06-08 15:48:20,781] [log.py:224] [log:log_response] [WARNING]- Not Found: /favicon.ico
[2021-06-08 15:48:20,782] [basehttp.py:161] [basehttp:log_message] [WARNING]- "GET /favicon.ico HTTP/1.1" 404 4041
[2021-06-08 15:48:23,083] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /login HTTP/1.1" 301 0
[2021-06-08 15:48:23,097] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /login/ HTTP/1.1" 200 2926
[2021-06-08 15:48:23,114] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /static/js/login.js HTTP/1.1" 200 1950
[2021-06-08 15:48:23,119] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /static/images/logo02.png HTTP/1.1" 200 8466
[2021-06-08 15:48:23,127] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /static/images/icons02.png HTTP/1.1" 200 3935
[2021-06-08 15:48:23,132] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /static/images/login_banner.png HTTP/1.1" 200 319312
[2021-06-08 15:48:23,140] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /static/images/QQ-weixin.png HTTP/1.1" 200 1816
[2021-06-08 15:48:30,106] [log.py:224] [log:log_response] [ERROR]- Internal Server Error: /login/
Traceback (most recent call last):
  File "D:\python\lib\site-packages\django_redis\cache.py", line 27, in _decorator
    return method(self, *args, **kwargs)
  File "D:\python\lib\site-packages\django_redis\cache.py", line 131, in has_key
    return self.client.has_key(*args, **kwargs)
  File "D:\python\lib\site-packages\django_redis\client\default.py", line 511, in has_key
    raise ConnectionInterrupted(connection=client) from e
django_redis.exceptions.ConnectionInterrupted: Redis ConnectionError: Error 10061 connecting to 127.0.0.1:6379. 由于目标计算机积极拒绝，无法连接。.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\python\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "D:\python\lib\site-packages\django\core\handlers\base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\python\lib\site-packages\django\views\generic\base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "D:\python\lib\site-packages\django\views\generic\base.py", line 98, in dispatch
    return handler(request, *args, **kwargs)
  File "E:\djangoProject\djangoProject\meiduo_project\apps\users\views.py", line 154, in post
    login(request, user)
  File "D:\python\lib\site-packages\django\contrib\auth\__init__.py", line 111, in login
    request.session.cycle_key()
  File "D:\python\lib\site-packages\django\contrib\sessions\backends\base.py", line 344, in cycle_key
    self.create()
  File "D:\python\lib\site-packages\django\contrib\sessions\backends\cache.py", line 43, in create
    self._session_key = self._get_new_session_key()
  File "D:\python\lib\site-packages\django\contrib\sessions\backends\base.py", line 196, in _get_new_session_key
    if not self.exists(session_key):
  File "D:\python\lib\site-packages\django\contrib\sessions\backends\cache.py", line 70, in exists
    return bool(session_key) and (self.cache_key_prefix + session_key) in self._cache
  File "D:\python\lib\site-packages\django\core\cache\backends\base.py", line 212, in __contains__
    return self.has_key(key)
  File "D:\python\lib\site-packages\django_redis\cache.py", line 34, in _decorator
    raise e.__cause__
  File "D:\python\lib\site-packages\django_redis\client\default.py", line 509, in has_key
    return client.exists(key) == 1
  File "D:\python\lib\site-packages\redis\client.py", line 1581, in exists
    return self.execute_command('EXISTS', *names)
  File "D:\python\lib\site-packages\redis\client.py", line 898, in execute_command
    conn = self.connection or pool.get_connection(command_name, **options)
  File "D:\python\lib\site-packages\redis\connection.py", line 1192, in get_connection
    connection.connect()
  File "D:\python\lib\site-packages\redis\connection.py", line 563, in connect
    raise ConnectionError(self._error_message(e))
redis.exceptions.ConnectionError: Error 10061 connecting to 127.0.0.1:6379. 由于目标计算机积极拒绝，无法连接。.
[2021-06-08 15:48:30,111] [basehttp.py:161] [basehttp:log_message] [ERROR]- "POST /login/ HTTP/1.1" 500 144877
[2021-06-08 15:49:02,995] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /login/ HTTP/1.1" 200 2926
[2021-06-08 15:49:03,025] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /static/js/login.js HTTP/1.1" 304 0
[2021-06-08 15:49:06,956] [basehttp.py:161] [basehttp:log_message] [INFO]- "POST /login/ HTTP/1.1" 302 0
[2021-06-08 15:49:06,962] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET / HTTP/1.1" 200 20506
[2021-06-08 15:49:07,041] [log.py:224] [log:log_response] [WARNING]- Not Found: /carts/simple/
[2021-06-08 15:49:07,041] [basehttp.py:161] [basehttp:log_message] [WARNING]- "GET /carts/simple/ HTTP/1.1" 404 4047
[2021-06-08 15:49:15,556] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /logout/ HTTP/1.1" 302 0
[2021-06-08 15:49:15,561] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET / HTTP/1.1" 200 20506
[2021-06-08 15:49:15,610] [log.py:224] [log:log_response] [WARNING]- Not Found: /carts/simple/
[2021-06-08 15:49:15,612] [basehttp.py:161] [basehttp:log_message] [WARNING]- "GET /carts/simple/ HTTP/1.1" 404 4047
[2021-06-08 15:49:16,493] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /login/ HTTP/1.1" 200 2926
[2021-06-08 15:49:17,798] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /qq/login/?next=/ HTTP/1.1" 200 153
[2021-06-08 15:49:35,636] [log.py:224] [log:log_response] [WARNING]- Not Found: /call_back
[2021-06-08 15:49:35,636] [basehttp.py:161] [basehttp:log_message] [WARNING]- "GET /call_back HTTP/1.1" 404 4035
[2021-06-08 15:49:53,612] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /oauth_callback HTTP/1.1" 301 0
[2021-06-08 15:49:53,619] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /oauth_callback/ HTTP/1.1" 200 4520
[2021-06-08 15:49:53,647] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /static/js/host.js HTTP/1.1" 200 80
[2021-06-08 15:49:53,655] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /static/js/oauth_callback.js HTTP/1.1" 200 4868
[2021-06-08 15:49:53,665] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /static/images/interval_line.png HTTP/1.1" 200 1123
[2021-06-08 15:49:53,666] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /static/images/register_banner.png HTTP/1.1" 200 54894
[2021-06-08 15:49:53,766] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /image_codes/698c038f-0b42-49fe-92e1-0a8454c091f4/ HTTP/1.1" 200 3542
[2021-06-08 15:50:07,404] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /sms_codes/15116340630/?image_code=xdaz&image_code_id=698c038f-0b42-49fe-92e1-0a8454c091f4 HTTP/1.1" 200 29
[2021-06-08 16:05:55,746] [autoreload.py:636] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2021-06-08 16:05:56,839] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET / HTTP/1.1" 200 20506
[2021-06-08 16:05:57,351] [basehttp.py:75] [basehttp:handle_error] [INFO]- - Broken pipe from ('127.0.0.1', 60254)

[2021-06-08 16:05:58,409] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET / HTTP/1.1" 200 20506
[2021-06-08 16:05:58,947] [log.py:224] [log:log_response] [WARNING]- Not Found: /favicon.ico
[2021-06-08 16:05:58,957] [log.py:224] [log:log_response] [WARNING]- Not Found: /carts/simple/
[2021-06-08 16:05:58,958] [basehttp.py:161] [basehttp:log_message] [WARNING]- "GET /favicon.ico HTTP/1.1" 404 4041
[2021-06-08 16:05:58,959] [basehttp.py:161] [basehttp:log_message] [WARNING]- "GET /carts/simple/ HTTP/1.1" 404 4047
[2021-06-08 16:06:05,441] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /oauth_callback/ HTTP/1.1" 200 4520
[2021-06-08 16:06:05,480] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /static/css/reset.css HTTP/1.1" 200 638
[2021-06-08 16:06:05,481] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /static/js/host.js HTTP/1.1" 200 80
[2021-06-08 16:06:05,483] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /static/js/axios-0.18.0.min.js HTTP/1.1" 200 12913
[2021-06-08 16:06:05,487] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /static/css/main.css HTTP/1.1" 200 39722
[2021-06-08 16:06:05,495] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /static/js/common.js HTTP/1.1" 200 891
[2021-06-08 16:06:05,501] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /static/js/oauth_callback.js HTTP/1.1" 200 4868
[2021-06-08 16:06:05,503] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /static/js/vue-2.5.16.js HTTP/1.1" 200 289387
[2021-06-08 16:06:05,510] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /static/images/logo.png HTTP/1.1" 200 7450
[2021-06-08 16:06:05,527] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /static/images/interval_line.png HTTP/1.1" 200 1123
[2021-06-08 16:06:05,532] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /static/images/register_banner.png HTTP/1.1" 200 54894
[2021-06-08 16:06:05,623] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /image_codes/addcab80-fd42-4a67-88e9-d1f92776e61f/ HTTP/1.1" 200 3265
[2021-06-08 16:08:28,340] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /oauth_callback/ HTTP/1.1" 200 4520
[2021-06-08 16:08:28,367] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /static/css/reset.css HTTP/1.1" 200 638
[2021-06-08 16:08:28,367] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /static/js/host.js HTTP/1.1" 200 80
[2021-06-08 16:08:28,369] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /static/js/axios-0.18.0.min.js HTTP/1.1" 200 12913
[2021-06-08 16:08:28,373] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /static/css/main.css HTTP/1.1" 200 39722
[2021-06-08 16:08:28,381] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /static/js/common.js HTTP/1.1" 200 891
[2021-06-08 16:08:28,383] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /static/js/vue-2.5.16.js HTTP/1.1" 200 289387
[2021-06-08 16:08:28,394] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /static/js/oauth_callback.js HTTP/1.1" 200 4868
[2021-06-08 16:08:28,396] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /static/images/logo.png HTTP/1.1" 200 7450
[2021-06-08 16:08:28,409] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /static/images/interval_line.png HTTP/1.1" 200 1123
[2021-06-08 16:08:28,412] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /static/images/register_banner.png HTTP/1.1" 200 54894
[2021-06-08 16:08:28,451] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /image_codes/118b17d3-4bd8-4773-91ca-36e8dafe7ba9/ HTTP/1.1" 200 3609
[2021-06-08 16:18:40,299] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /sms_codes/15116340630/?image_code=pd&image_code_id=118b17d3-4bd8-4773-91ca-36e8dafe7ba9 HTTP/1.1" 200 60
[2021-06-08 16:18:40,320] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /image_codes/b1273d92-7236-4b91-86dc-acf8f4ac7ecd/ HTTP/1.1" 200 2964
[2021-06-08 16:19:36,894] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /sms_codes/15116340630/?image_code=bjkc&image_code_id=b1273d92-7236-4b91-86dc-acf8f4ac7ecd HTTP/1.1" 200 29
[2021-06-08 16:21:21,796] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /oauth_callback/ HTTP/1.1" 200 4477
[2021-06-08 16:21:21,833] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /static/css/reset.css HTTP/1.1" 200 638
[2021-06-08 16:21:21,838] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /static/js/host.js HTTP/1.1" 200 80
[2021-06-08 16:21:21,843] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /static/js/axios-0.18.0.min.js HTTP/1.1" 200 12913
[2021-06-08 16:21:21,849] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /static/css/main.css HTTP/1.1" 200 39722
[2021-06-08 16:21:21,855] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /static/js/common.js HTTP/1.1" 200 891
[2021-06-08 16:21:21,865] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /static/js/oauth_callback.js HTTP/1.1" 200 4868
[2021-06-08 16:21:21,869] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /static/js/vue-2.5.16.js HTTP/1.1" 200 289387
[2021-06-08 16:21:21,876] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /static/images/logo.png HTTP/1.1" 200 7450
[2021-06-08 16:21:21,893] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /static/images/interval_line.png HTTP/1.1" 200 1123
[2021-06-08 16:21:21,897] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /static/images/register_banner.png HTTP/1.1" 200 54894
[2021-06-08 16:21:27,048] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /image_codes/ac2c8a85-c9f9-4222-9a23-b90fb518aa87/ HTTP/1.1" 200 3060
[2021-06-08 16:21:49,444] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /oauth_callback/ HTTP/1.1" 200 4481
[2021-06-08 16:21:49,472] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /static/css/reset.css HTTP/1.1" 200 638
[2021-06-08 16:21:49,472] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /static/js/host.js HTTP/1.1" 200 80
[2021-06-08 16:21:49,475] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /static/js/axios-0.18.0.min.js HTTP/1.1" 200 12913
[2021-06-08 16:21:49,477] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /static/css/main.css HTTP/1.1" 200 39722
[2021-06-08 16:21:49,484] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /static/js/common.js HTTP/1.1" 200 891
[2021-06-08 16:21:49,487] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /static/js/vue-2.5.16.js HTTP/1.1" 200 289387
[2021-06-08 16:21:49,495] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /static/images/logo.png HTTP/1.1" 200 7450
[2021-06-08 16:21:49,496] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /static/js/oauth_callback.js HTTP/1.1" 200 4868
[2021-06-08 16:21:49,511] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /static/images/interval_line.png HTTP/1.1" 200 1123
[2021-06-08 16:21:49,513] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /static/images/register_banner.png HTTP/1.1" 200 54894
[2021-06-08 16:21:50,972] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /image_codes/048e6543-771f-4e46-bdcf-1f0a17279996/ HTTP/1.1" 200 3162
[2021-06-08 16:30:48,942] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /oauth_callback/ HTTP/1.1" 200 4634
[2021-06-08 16:30:48,975] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /static/css/reset.css HTTP/1.1" 200 638
[2021-06-08 16:30:48,979] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /static/js/host.js HTTP/1.1" 200 80
[2021-06-08 16:30:48,984] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /static/css/main.css HTTP/1.1" 200 39722
[2021-06-08 16:30:48,984] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /static/js/axios-0.18.0.min.js HTTP/1.1" 200 12913
[2021-06-08 16:30:48,993] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /static/js/common.js HTTP/1.1" 200 891
[2021-06-08 16:30:48,999] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /static/js/vue-2.5.16.js HTTP/1.1" 200 289387
[2021-06-08 16:30:49,004] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /static/js/oauth_callback.js HTTP/1.1" 200 4868
[2021-06-08 16:30:49,007] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /static/images/logo.png HTTP/1.1" 200 7450
[2021-06-08 16:30:49,021] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /static/images/interval_line.png HTTP/1.1" 200 1123
[2021-06-08 16:30:49,025] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /static/images/register_banner.png HTTP/1.1" 200 54894
[2021-06-08 16:30:50,845] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /image_codes/63946f07-e70a-44de-a646-ba47cc4d2868/ HTTP/1.1" 200 3551
[2021-06-08 17:05:24,618] [autoreload.py:250] [autoreload:trigger_reload] [INFO]- E:\djangoProject\djangoProject\meiduo_project\apps\oauthh\views.py changed, reloading.
[2021-06-08 17:05:26,196] [autoreload.py:636] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2021-06-08 17:06:16,118] [autoreload.py:250] [autoreload:trigger_reload] [INFO]- E:\djangoProject\djangoProject\meiduo_project\apps\oauthh\views.py changed, reloading.
[2021-06-08 17:06:17,514] [autoreload.py:636] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2021-06-08 17:07:33,494] [autoreload.py:250] [autoreload:trigger_reload] [INFO]- E:\djangoProject\djangoProject\meiduo_project\apps\oauthh\utils.py changed, reloading.
[2021-06-08 17:07:34,883] [autoreload.py:636] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2021-06-08 17:19:47,017] [autoreload.py:250] [autoreload:trigger_reload] [INFO]- E:\djangoProject\djangoProject\meiduo_project\apps\oauthh\views.py changed, reloading.
[2021-06-08 17:19:48,540] [autoreload.py:636] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2021-06-08 17:19:56,005] [autoreload.py:250] [autoreload:trigger_reload] [INFO]- E:\djangoProject\djangoProject\meiduo_project\apps\oauthh\views.py changed, reloading.
[2021-06-08 17:19:57,460] [autoreload.py:636] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2021-06-08 17:35:13,363] [autoreload.py:250] [autoreload:trigger_reload] [INFO]- E:\djangoProject\djangoProject\meiduo_project\apps\oauthh\views.py changed, reloading.
[2021-06-08 17:35:14,899] [autoreload.py:636] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2021-06-08 17:35:28,011] [autoreload.py:250] [autoreload:trigger_reload] [INFO]- E:\djangoProject\djangoProject\meiduo_project\apps\oauthh\views.py changed, reloading.
[2021-06-08 17:35:29,540] [autoreload.py:636] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2021-06-08 17:43:59,028] [autoreload.py:636] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2021-06-08 17:44:00,107] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET / HTTP/1.1" 200 20506
[2021-06-08 17:44:00,672] [basehttp.py:75] [basehttp:handle_error] [INFO]- - Broken pipe from ('127.0.0.1', 58278)

[2021-06-08 17:44:01,906] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET / HTTP/1.1" 200 20506
[2021-06-08 17:44:02,421] [log.py:224] [log:log_response] [WARNING]- Not Found: /carts/simple/
[2021-06-08 17:44:02,423] [basehttp.py:161] [basehttp:log_message] [WARNING]- "GET /carts/simple/ HTTP/1.1" 404 4047
[2021-06-08 17:44:02,436] [log.py:224] [log:log_response] [WARNING]- Not Found: /favicon.ico
[2021-06-08 17:44:02,438] [basehttp.py:161] [basehttp:log_message] [WARNING]- "GET /favicon.ico HTTP/1.1" 404 4041
[2021-06-08 17:44:30,072] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /oauth_callback HTTP/1.1" 301 0
[2021-06-08 17:44:30,083] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /oauth_callback/ HTTP/1.1" 200 4631
[2021-06-08 17:44:30,108] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /static/js/host.js HTTP/1.1" 200 80
[2021-06-08 17:44:30,118] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /static/js/oauth_callback.js HTTP/1.1" 200 4868
[2021-06-08 17:44:30,205] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /image_codes/cdb5cac9-ee79-4490-9cc6-a2917e9bfdd2/ HTTP/1.1" 200 2892
[2021-06-08 17:44:42,387] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /image_codes/a6c336b3-e2a7-44ed-b9ac-dad22814e3e4/ HTTP/1.1" 200 3823
[2021-06-08 17:45:18,182] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /sms_codes/15116340630/?image_code=4xuw&image_code_id=a6c336b3-e2a7-44ed-b9ac-dad22814e3e4 HTTP/1.1" 200 29
[2021-06-08 17:45:35,888] [log.py:224] [log:log_response] [ERROR]- Internal Server Error: /oauth_callback/
Traceback (most recent call last):
  File "D:\python\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "D:\python\lib\site-packages\django\core\handlers\base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\python\lib\site-packages\django\views\generic\base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "D:\python\lib\site-packages\django\views\generic\base.py", line 98, in dispatch
    return handler(request, *args, **kwargs)
  File "E:\djangoProject\djangoProject\meiduo_project\apps\oauthh\views.py", line 71, in post
    openid = get_access_token(accesstoken)
  File "E:\djangoProject\djangoProject\meiduo_project\apps\oauthh\utils.py", line 16, in get_access_token
    data = s.loads(token)
  File "D:\python\lib\site-packages\itsdangerous\jws.py", line 217, in loads
    payload, header = super().loads(s, salt, return_header=True)
  File "D:\python\lib\site-packages\itsdangerous\jws.py", line 169, in loads
    self.make_signer(salt, self.algorithm).unsign(want_bytes(s)),
  File "D:\python\lib\site-packages\itsdangerous\signer.py", line 240, in unsign
    raise BadSignature(f"No {self.sep!r} found in value")
itsdangerous.exc.BadSignature: No b'.' found in value
[2021-06-08 17:45:45,757] [basehttp.py:161] [basehttp:log_message] [ERROR]- "POST /oauth_callback/ HTTP/1.1" 500 97677
[2021-06-08 17:46:08,764] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /image_codes/80aabde1-c0ad-4c92-945a-06c53efbec23/ HTTP/1.1" 200 3421
[2021-06-08 17:48:33,333] [autoreload.py:636] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2021-06-08 17:48:34,375] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET / HTTP/1.1" 200 20506
[2021-06-08 17:48:35,506] [basehttp.py:75] [basehttp:handle_error] [INFO]- - Broken pipe from ('127.0.0.1', 63983)

[2021-06-08 17:48:36,342] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET / HTTP/1.1" 200 20506
[2021-06-08 17:48:36,802] [log.py:224] [log:log_response] [WARNING]- Not Found: /carts/simple/
[2021-06-08 17:48:36,810] [log.py:224] [log:log_response] [WARNING]- Not Found: /favicon.ico
[2021-06-08 17:48:36,812] [basehttp.py:161] [basehttp:log_message] [WARNING]- "GET /carts/simple/ HTTP/1.1" 404 4047
[2021-06-08 17:48:36,813] [basehttp.py:161] [basehttp:log_message] [WARNING]- "GET /favicon.ico HTTP/1.1" 404 4041
[2021-06-08 17:48:39,605] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /center HTTP/1.1" 301 0
[2021-06-08 17:48:39,612] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /center/ HTTP/1.1" 302 0
[2021-06-08 17:48:39,628] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /login/?next=/center/ HTTP/1.1" 200 2926
[2021-06-08 17:48:39,665] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /static/js/login.js HTTP/1.1" 200 1950
[2021-06-08 17:48:39,666] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /static/images/logo02.png HTTP/1.1" 200 8466
[2021-06-08 17:48:39,673] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /static/images/login_banner.png HTTP/1.1" 200 319312
[2021-06-08 17:48:39,681] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /static/images/QQ-weixin.png HTTP/1.1" 200 1816
[2021-06-08 17:48:44,687] [basehttp.py:161] [basehttp:log_message] [INFO]- "POST /login/?next=/center/ HTTP/1.1" 302 0
[2021-06-08 17:48:44,693] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET / HTTP/1.1" 200 20506
[2021-06-08 17:48:44,772] [log.py:224] [log:log_response] [WARNING]- Not Found: /carts/simple/
[2021-06-08 17:48:44,774] [basehttp.py:161] [basehttp:log_message] [WARNING]- "GET /carts/simple/ HTTP/1.1" 404 4047
[2021-06-08 17:48:47,119] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /center/ HTTP/1.1" 200 4515
[2021-06-08 17:48:47,142] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /static/images/goods/goods006.jpg HTTP/1.1" 200 6836
[2021-06-08 17:48:47,143] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /static/images/goods/goods007.jpg HTTP/1.1" 200 3936
[2021-06-08 17:48:47,147] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /static/images/left_bg.jpg HTTP/1.1" 200 1367
[2021-06-08 17:48:47,148] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /static/images/shop_cart.png HTTP/1.1" 200 1317
[2021-06-08 17:50:40,556] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /logout/ HTTP/1.1" 302 0
[2021-06-08 17:50:40,562] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET / HTTP/1.1" 200 20506
[2021-06-08 17:50:40,625] [log.py:224] [log:log_response] [WARNING]- Not Found: /carts/simple/
[2021-06-08 17:50:40,628] [basehttp.py:161] [basehttp:log_message] [WARNING]- "GET /carts/simple/ HTTP/1.1" 404 4047
[2021-06-08 17:50:41,523] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /center/ HTTP/1.1" 302 0
[2021-06-08 17:50:41,530] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /login/?next=/center/ HTTP/1.1" 200 2926
[2021-06-08 18:00:20,837] [autoreload.py:250] [autoreload:trigger_reload] [INFO]- E:\djangoProject\djangoProject\meiduo_project\apps\users\views.py changed, reloading.
[2021-06-08 18:00:22,264] [autoreload.py:636] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2021-06-08 18:00:37,053] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET / HTTP/1.1" 200 20506
[2021-06-08 18:00:37,197] [log.py:224] [log:log_response] [WARNING]- Not Found: /carts/simple/
[2021-06-08 18:00:37,198] [basehttp.py:161] [basehttp:log_message] [WARNING]- "GET /carts/simple/ HTTP/1.1" 404 4047
[2021-06-08 18:00:38,615] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /center/ HTTP/1.1" 302 0
[2021-06-08 18:00:38,630] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /login/?next=/center/ HTTP/1.1" 200 2926
[2021-06-08 18:00:44,502] [log.py:224] [log:log_response] [ERROR]- Internal Server Error: /login/
Traceback (most recent call last):
  File "D:\python\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "D:\python\lib\site-packages\django\core\handlers\base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\python\lib\site-packages\django\views\generic\base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "D:\python\lib\site-packages\django\views\generic\base.py", line 98, in dispatch
    return handler(request, *args, **kwargs)
  File "E:\djangoProject\djangoProject\meiduo_project\apps\users\views.py", line 164, in post
    response = redirect(reverse(next_url))
  File "D:\python\lib\site-packages\django\urls\base.py", line 86, in reverse
    return resolver._reverse_with_prefix(view, prefix, *args, **kwargs)
  File "D:\python\lib\site-packages\django\urls\resolvers.py", line 694, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for '/center/' not found. '/center/' is not a valid view function or pattern name.
[2021-06-08 18:00:44,505] [basehttp.py:161] [basehttp:log_message] [ERROR]- "POST /login/?next=/center/ HTTP/1.1" 500 93739
[2021-06-08 18:01:59,222] [log.py:224] [log:log_response] [ERROR]- Internal Server Error: /login/
Traceback (most recent call last):
  File "D:\python\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "D:\python\lib\site-packages\django\core\handlers\base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\python\lib\site-packages\django\views\generic\base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "D:\python\lib\site-packages\django\views\generic\base.py", line 98, in dispatch
    return handler(request, *args, **kwargs)
  File "E:\djangoProject\djangoProject\meiduo_project\apps\users\views.py", line 164, in post
    response = redirect(reverse(next_url))
  File "D:\python\lib\site-packages\django\urls\base.py", line 86, in reverse
    return resolver._reverse_with_prefix(view, prefix, *args, **kwargs)
  File "D:\python\lib\site-packages\django\urls\resolvers.py", line 694, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for '/center/' not found. '/center/' is not a valid view function or pattern name.
[2021-06-08 18:01:59,222] [log.py:224] [log:log_response] [ERROR]- Internal Server Error: /login/
Traceback (most recent call last):
  File "D:\python\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "D:\python\lib\site-packages\django\core\handlers\base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\python\lib\site-packages\django\views\generic\base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "D:\python\lib\site-packages\django\views\generic\base.py", line 98, in dispatch
    return handler(request, *args, **kwargs)
  File "E:\djangoProject\djangoProject\meiduo_project\apps\users\views.py", line 164, in post
    response = redirect(reverse(next_url))
  File "D:\python\lib\site-packages\django\urls\base.py", line 86, in reverse
    return resolver._reverse_with_prefix(view, prefix, *args, **kwargs)
  File "D:\python\lib\site-packages\django\urls\resolvers.py", line 694, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for '/center/' not found. '/center/' is not a valid view function or pattern name.
[2021-06-08 18:01:59,228] [basehttp.py:75] [basehttp:handle_error] [INFO]- - Broken pipe from ('127.0.0.1', 50436)

[2021-06-08 18:01:59,233] [basehttp.py:161] [basehttp:log_message] [ERROR]- "POST /login/?next=/center/ HTTP/1.1" 500 93739
[2021-06-08 18:03:52,222] [autoreload.py:250] [autoreload:trigger_reload] [INFO]- E:\djangoProject\djangoProject\meiduo_project\apps\users\views.py changed, reloading.
[2021-06-08 18:03:53,655] [autoreload.py:636] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2021-06-08 18:03:55,740] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /login/ HTTP/1.1" 200 2926
[2021-06-08 18:03:55,785] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /static/js/login.js HTTP/1.1" 304 0
[2021-06-08 18:04:12,286] [basehttp.py:161] [basehttp:log_message] [INFO]- "POST /login/ HTTP/1.1" 302 0
[2021-06-08 18:04:12,306] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET / HTTP/1.1" 200 20506
[2021-06-08 18:04:12,373] [log.py:224] [log:log_response] [WARNING]- Not Found: /carts/simple/
[2021-06-08 18:04:12,373] [basehttp.py:161] [basehttp:log_message] [WARNING]- "GET /carts/simple/ HTTP/1.1" 404 4047
[2021-06-08 18:04:14,231] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /logout/ HTTP/1.1" 302 0
[2021-06-08 18:04:14,238] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET / HTTP/1.1" 200 20506
[2021-06-08 18:04:14,297] [log.py:224] [log:log_response] [WARNING]- Not Found: /carts/simple/
[2021-06-08 18:04:14,298] [basehttp.py:161] [basehttp:log_message] [WARNING]- "GET /carts/simple/ HTTP/1.1" 404 4047
[2021-06-08 18:04:15,125] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /login HTTP/1.1" 301 0
[2021-06-08 18:04:15,132] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /login/ HTTP/1.1" 200 2926
[2021-06-08 18:04:18,706] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /center/ HTTP/1.1" 302 0
[2021-06-08 18:04:18,714] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /login/?next=/center/ HTTP/1.1" 200 2926
[2021-06-08 18:04:41,960] [log.py:224] [log:log_response] [ERROR]- Internal Server Error: /login/
Traceback (most recent call last):
  File "D:\python\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "D:\python\lib\site-packages\django\core\handlers\base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\python\lib\site-packages\django\views\generic\base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "D:\python\lib\site-packages\django\views\generic\base.py", line 98, in dispatch
    return handler(request, *args, **kwargs)
  File "E:\djangoProject\djangoProject\meiduo_project\apps\users\views.py", line 164, in post
    response = redirect(reverse(next_url.repalce('/','')))
AttributeError: 'str' object has no attribute 'repalce'
[2021-06-08 18:04:41,965] [basehttp.py:161] [basehttp:log_message] [ERROR]- "POST /login/?next=/center/ HTTP/1.1" 500 83575
[2021-06-08 18:05:07,406] [autoreload.py:250] [autoreload:trigger_reload] [INFO]- E:\djangoProject\djangoProject\meiduo_project\apps\users\views.py changed, reloading.
[2021-06-08 18:05:08,846] [autoreload.py:636] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2021-06-08 18:05:10,806] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /login/?next=/center/ HTTP/1.1" 200 2926
[2021-06-08 18:05:43,783] [basehttp.py:161] [basehttp:log_message] [INFO]- "POST /login/?next=/center/ HTTP/1.1" 302 0
[2021-06-08 18:05:43,811] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /center/ HTTP/1.1" 200 4515
[2021-06-08 18:19:03,914] [autoreload.py:250] [autoreload:trigger_reload] [INFO]- E:\djangoProject\djangoProject\meiduo_project\apps\users\views.py changed, reloading.
[2021-06-08 18:19:05,265] [autoreload.py:636] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2021-06-08 18:21:23,822] [autoreload.py:250] [autoreload:trigger_reload] [INFO]- E:\djangoProject\djangoProject\meiduo_project\apps\users\views.py changed, reloading.
[2021-06-08 18:21:25,345] [autoreload.py:636] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2021-06-08 18:22:21,664] [autoreload.py:250] [autoreload:trigger_reload] [INFO]- E:\djangoProject\djangoProject\meiduo_project\apps\users\views.py changed, reloading.
[2021-06-08 18:22:23,041] [autoreload.py:636] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2021-06-08 18:23:00,901] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /center/ HTTP/1.1" 200 4499
[2021-06-08 18:24:25,531] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /center/ HTTP/1.1" 200 4718
[2021-06-08 18:24:34,726] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /center/ HTTP/1.1" 200 4721
